name: Build and Run Dev Server

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Save build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ./dist

      - name: Show artifact path
        run: 'echo "Artifact saved at: $GITHUB_WORKSPACE/dist"'

      - name: Run Dev Server temporarily
        run: |
          echo "Starting Dev Server..."
          npm run dev &             # run in background
          DEV_PID=$!
          sleep 10                  # simulate server running time
          echo "Stopping Dev Server..."
          kill $DEV_PID || true     # stop the server if still running

