name: Build and Serve Static App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-serve:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build --if-present

      - name: Save build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ./dist

      - name: Install http-server
        run: npm install -g http-server

      - name: Run http-server
        run: |
          echo "Running static server..."
          nohup http-server ./dist -p 8080 &
          sleep 10
          echo "Killing static server..."
          pkill -f "http-server" || true


